apiVersion: v1
kind: Pod
metadata:
  name: cpu-hog
  namespace: default
spec:
  containers:
    - name: cpu-hog
      image: progrium/stress
      command: ["stress"]
      args: ["--cpu", "2", "--timeout", "300"]
      resources:
        limits:
          cpu: "2"
          memory: "256Mi"
        requests:
          cpu: "1"
          memory: "128Mi"
