apiVersion: v1
kind: Pod
metadata:
  name: notready-pod
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
      readinessProbe:
        exec:
          command:
            - cat
            - /doesnotexist
        initialDelaySeconds: 5
        periodSeconds: 5
