apiVersion: v1
kind: Pod
metadata:
  name: traffic-hog
  namespace: default
spec:
  containers:
    - name: traffic-hog
      image: curlimages/curl:8.8.0
      command: ["/bin/sh"]
      args:
        - -c
        - |
          for i in $(seq 1 300); do
            curl -k -s https://www.ushasree.xyz/ > /dev/null
            sleep 1
          done
      resources:
        requests:
          cpu: "0.5"
          memory: "64Mi"
        limits:
          cpu: "1"
          memory: "128Mi"
