name: Infra + EKS Deploy (One Flow)

on:
  push:
    branches: [ main ]
    paths:
      - 'Infra/**'
      - 'eks-apps/**'
      - '.github/workflows/infra-and-deploy.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION || vars.AWS_REGION || 'ap-south-1' }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME || 'ushasreestores-eks' }}
  TF_STATE_BUCKET: ${{ secrets.TF_STATE_BUCKET || vars.TF_STATE_BUCKET || 'ushasreestores-s3-tfstate' }}
  TF_STATE_DYNAMODB_TABLE: ${{ secrets.TF_STATE_DYNAMODB_TABLE || vars.TF_STATE_DYNAMODB_TABLE || 'ushasreestores-s3-tflock' }}
  TF_STATE_KEY: ${{ secrets.TF_STATE_KEY || 'infra/terraform.tfstate' }}
  TF_IN_AUTOMATION: true
  TF_INPUT: 0

jobs:
  infra_and_deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: infra-and-deploy-${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using access keys (your logs show AK/SK), keep this.
      # If you move to OIDC, replace with role-to-assume instead.
      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Show TF & AWS context
        run: |
          terraform -version
          aws sts get-caller-identity
          echo "Bucket: ${TF_STATE_BUCKET}  Table: ${TF_STATE_DYNAMODB_TABLE}  Key: ${TF_STATE_KEY}"

      # ---------- BOOTSTRAP (LOCAL backend) ----------
      # Only create bucket/table if they don't exist; else skip.
      - name: Check backend resources
        id: backend_exists
        run: |
          set -e
          need_bootstrap=0
          if ! aws s3api head-bucket --bucket "${TF_STATE_BUCKET}" 2>/dev/null; then
            need_bootstrap=1
          fi
          if ! aws dynamodb describe-table --table-name "${TF_STATE_DYNAMODB_TABLE}" >/dev/null 2>&1; then
            need_bootstrap=1
          fi
          echo "need_bootstrap=${need_bootstrap}" >> "$GITHUB_OUTPUT"

      - name: Terraform init (LOCAL, no backend)
        if: steps.backend_exists.outputs.need_bootstrap == '1'
        run: terraform -chdir=Infra init -reconfigure -backend=false

      - name: Create S3 & DynamoDB (bootstrap)
        if: steps.backend_exists.outputs.need_bootstrap == '1'
        run: |
          set -euo pipefail
          terraform -chdir=Infra apply -auto-approve \
            -target=aws_s3_bucket.tfstate \
            -target=aws_s3_bucket_versioning.tfstate \
            -target=aws_s3_bucket_server_side_encryption_configuration.tfstate \
            -target=aws_dynamodb_table.tf_lock

      # ---------- RE-INIT TO S3 BACKEND (REQUIRED) ----------
      - name: Terraform init (S3 backend, reconfigure)
        run: |
          set -euo pipefail
          terraform -chdir=Infra init -reconfigure \
            -backend-config="bucket=${TF_STATE_BUCKET}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_STATE_DYNAMODB_TABLE}" \
            -backend-config="encrypt=true"
          ls -al Infra/.terraform || true

      - name: Terraform validate
        run: terraform -chdir=Infra validate

      # Optional fmt that won't fail pipeline on exit code 3
      - name: Terraform fmt (non-blocking)
        run: |
          set +e
          terraform -chdir=Infra fmt -check -recursive
          status=$?
          if [ $status -eq 3 ]; then
            echo "::warning::Run 'terraform fmt -recursive' locally to fix formatting."
            terraform -chdir=Infra fmt -diff -recursive || true
            exit 0
          fi
          exit $status

      # ---------- FULL APPLY ----------
      - name: Terraform plan
        run: terraform -chdir=Infra plan -input=false -out=tfplan.bin

      - name: Terraform apply
        run: terraform -chdir=Infra apply -input=false -auto-approve tfplan.bin

      # ---------- EKS DEPLOY ----------
      - name: Wait for EKS ACTIVE
        run: aws eks wait cluster-active --name "$EKS_CLUSTER_NAME"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Update kubeconfig & quick check
        run: |
          set -euo pipefail
          aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$AWS_REGION"
          kubectl version --short || true
          kubectl get nodes -o wide

      - name: Make scripts executable
        run: |
          chmod +x eks-apps/deployapps.sh || true
          chmod +x eks-apps/appsdeploy.sh || true
          chmod +x eks-apps/argocd/argocd.sh || true
          chmod +x eks-apps/nginx-ingress/*.sh || true
          chmod +x eks-apps/monitoring/monitoring.sh || true

      - name: Deploy apps (deployapps.sh)
        run: |
          set -euo pipefail
          ./eks-apps/deployapps.sh

      - name: Post-deploy sanity
        run: |
          kubectl get ns
          kubectl get pods -A
          kubectl get svc -A
          kubectl get ingress -A

      - name: Collect diagnostics on failure
        if: failure()
        run: |
          mkdir -p diag
          kubectl get nodes -o wide > diag/nodes.txt || true
          kubectl get pods -A -o wide > diag/pods.txt || true
          kubectl describe pods -A > diag/pods_describe.txt || true
          kubectl get events -A --sort-by=.lastTimestamp > diag/events.txt || true
          kubectl get ing -A -o yaml > diag/ingresses.yaml || true
          kubectl get svc -A -o yaml > diag/services.yaml || true

      - name: Upload diagnostics
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: k8s-diagnostics
          path: diag/
